### PR TITLE
fix unresponsive directions popup on state change

### LINKED ISSUE #272: [Bug]: selecting navigation to class via schedule view breaks directions
### Bug Description

navigation to class via schedule view, tapping route button, breaks directions display

### Steps to Reproduce

open schedule view
click on a buildign with a class
start route to a class

### Expected Behavior

shows routes, times and intructions to class
the schedule view toggle is not interactable

### Actual Behavior

directions popup si broken
not routes or times displayed
popup does not close

Image

### Environment

_No response_

### Logs / Screenshots

```shell

```

### Confirmation

- [x] I have searched existing issues to make sure this bug has not been reported.

### PR DESCRIPTION
**Pull request by dokilax**
fixes #272 
fix directions pop up unresponsive on campus toggle and from schedule view
fix switching walk -> transit not updating dots to line
added the circle at transport mode change points
update tests with changes

### CODE REVIEW

File: frontend/conuwalks/src/components/CampusMap.tsx [hunk 1]
```diff
@@ -262,9 +269,18 @@ const CampusMap: React.FC<CampusMapProps> = ({
...
-      clearDestination();
-      setSelectedBuilding((prev) => ({ ...prev, visible: false }));
+      // do if we just acted in schedule view
+      if (!showDirections && !isNavigationActive) {
+        destinationPopupRef.current?.dismiss();
+        setTimeout(() => {
+          clearDestination();
+          setSelectedBuilding((prev) => ({ ...prev, visible: false }));
+        }, 250);
+      }
```
Comment (yas176) [inline frontend/conuwalks/src/components/CampusMap.tsx]: Can we store/clear this setTimeout via a ref (and clear on unmount)? If this runs multiple times or the component unmounts, the delayed callback can fire later and apply stale state changes / cause “state update on unmounted component” warnings. 

if (!showDirections && !isNavigationActive) {
  destinationPopupRef.current?.dismiss();

  if (dismissTimeoutRef.current) {
    clearTimeout(dismissTimeoutRef.current);
    dismissTimeoutRef.current = null;
  }

  dismissTimeoutRef.current = setTimeout(() => {
    clearDestination();
    setSelectedBuilding((prev) => ({ ...prev, visible: false }));
  }, DISMISS_DELAY_MS);
}

File: frontend/conuwalks/src/components/CampusMap.tsx [hunk 2]
```diff
@@ -797,14 +813,24 @@ const CampusMap: React.FC<CampusMapProps> = ({
...
+                    onLayout={() => {
+                      if (trackDestMarker) {
+                        // Wait 250ms for the MaterialIcon to load, then freeze it
+                        setTimeout(() => setTrackDestMarker(false), 250);
+                      }
+                    }}
+                  >
+                    <MaterialIcons name="place" size={26} color="#B03060" />
+                  </View>
                 </Marker>
```
Comment (yas176) [inline frontend/conuwalks/src/components/CampusMap.tsx]: Also here you can replace it with something like this

<View
  onLayout={() => {
    if (!trackDestMarker) return;

    if (trackMarkerTimeoutRef.current) {
      clearTimeout(trackMarkerTimeoutRef.current);
      trackMarkerTimeoutRef.current = null;
    }

   
    trackMarkerTimeoutRef.current = setTimeout(() => {
      setTrackDestMarker(false);
    }, ICON_FREEZE_DELAY_MS);
  }}
>
  <MaterialIcons name="place" size={26} color="#B03060" />
</View>

File: frontend/conuwalks/src/components/CampusMap.tsx [hunk 3]
```diff
@@ -262,9 +269,18 @@ const CampusMap: React.FC<CampusMapProps> = ({
         500,
       );
 
-      clearDestination();
-      setSelectedBuilding((prev) => ({ ...prev, visible: false }));
+      // do if we just acted in schedule view
+      if (!showDirections && !isNavigationActive) {
+        destinationPopupRef.current?.dismiss();
+        setTimeout(() => {
```
Comment (yas176) [inline frontend/conuwalks/src/components/CampusMap.tsx]: Can we store/clear this setTimeout via a ref (and clear on unmount)? If this runs multiple times or the component unmounts, the delayed callback can fire later and apply stale state changes / cause “state update on unmounted component” warnings. 

if (!showDirections && !isNavigationActive) {
  destinationPopupRef.current?.dismiss();

  if (dismissTimeoutRef.current) {
    clearTimeout(dismissTimeoutRef.current);
    dismissTimeoutRef.current = null;
  }

  dismissTimeoutRef.current = setTimeout(() => {
    clearDestination();
    setSelectedBuilding((prev) => ({ ...prev, visible: false }));
  }, DISMISS_DELAY_MS);
}

Comment (dokilax) [reply frontend/conuwalks/src/components/CampusMap.tsx]: thanks, nice catch.

File: frontend/conuwalks/src/components/RoutePolyline.tsx [hunk 4]
```diff
@@ -52,14 +51,57 @@ const getStepColorAndStyle = (step: DirectionStep, isIOS: boolean) => {
...
+      coordinate={coordinate}
+      anchor={{ x: 0.5, y: 0.5 }}
+      zIndex={zIndex}
+      tracksViewChanges={trackChanges}
+      flat
+    >
+      <View
+        onLayout={() => {
+          if (trackChanges) {
+            setTimeout(() => setTrackChanges(false), 250);
```
[the remark this answers is not in the document]
Comment (dokilax) [reply frontend/conuwalks/src/components/RoutePolyline.tsx]: ditto for this
